//Order is L, then R, then U, then D.  Any modifiers(entrance/exit/etc) comes afterward.
var roadLD = initImage("RoadLD.png")
var roadLR = initImage("RoadLR.jpg")
var roadUD = initImage("RoadUD.jpg")
var roadLU = initImage("RoadLU.png")
var roadRD = initImage("RoadRD.png")
var roadRU = initImage("RoadRU.png")
var grass = initImage("grass.png")
var end = initImage("endU.png")
var grassRock = initImage("grassRock.png")
var water = initImage("water/Water.png")
var deepWater = initImage("water/deepWater.png")
var entranceIndicator = initImage("EntranceIndicator.png")
var exitIndicatorUp = initImage("ExitIndicatorU.png")
var waterCover = initImage("waterCover.png")
var lightWaterCover = initImage("lightWaterCover.png")
var entrance = {x: 0, y: 0}
var exit = {x:-88, y:-88}
var trackInfo = [
//Row 1
[{track:true, x:0, y:0, tower:false, typeTrack:roadLR, trackDetails: entranceIndicator}, 
{track:true, x:1, y:0, tower:false, typeTrack:roadLR},
{track:true, x:2, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:3, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:4, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:5, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:6, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:7, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:8, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:9, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:10, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:11, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:12, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:13, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:14, y:0, tower:false, typeTrack:roadLR}, 
{track:true, x:15, y:0, tower:false, typeTrack:roadLD}],
//Row 2
[{track: false, x: 0, y:1, tower:false, typeTrack: grass}, 
{track: false, x: 1, y:1, tower:false, typeTrack: grass},
{track: false, x: 2, y:1, tower:false, typeTrack: grass},
{track: false, x: 3, y:1, tower:false, typeTrack: grass},
{track: false, x: 4, y:1, tower:false, typeTrack: grass},
{track: false, x: 5, y:1, tower:false, typeTrack: grass},
{track: false, x: 6, y:1, tower:false, typeTrack: grass},
{track: false, x: 7, y:1, tower:false, typeTrack: grass},
{track: false, x: 8, y:1, tower:false, typeTrack: grass},  
{track: false, x: 9, y:1, tower:false, typeTrack: grass},
{track: false, x: 10, y:1, tower:false, typeTrack: grass},
{track: false, x: 11, y:1, tower:false, typeTrack: grass},
{track: false, x: 12, y:1, tower:false, typeTrack: grass}, 
{track: false, x: 13, y:1, tower:false, typeTrack: grass}, 
{track: false, x: 14, y:1, tower:false, typeTrack: grass},
{track: true, x:15, y:1, tower:false, typeTrack:roadUD}],
//Row 3
[{track: true, x: 0, y: 2, tower: false, typeTrack: roadRD},
{track: true, x: 1, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 2, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 3, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 4, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 5, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 6, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 7, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 8, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 9, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 10, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 11, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 12, y: 2, tower: false, typeTrack: roadLR}, 
{track: true, x: 13, y: 2, tower: false, typeTrack: roadLD}, 
{track: false, x: 14, y: 2, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 2, tower: false, typeTrack:roadUD}],
//Row 4
[{track: true, x: 0, y: 3, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 3, tower: false, typeTrack: grassRock}, 
{track: false, x: 2, y: 3, tower: false, typeTrack: grass}, 
{track: false, x: 3, y: 3, tower: false, typeTrack: water}, 
{track: false, x: 4, y: 3, tower: false, typeTrack: water}, 
{track: false, x: 5, y: 3, tower: false, typeTrack: deepWater}, 
{track: false, x: 6, y: 3, tower: false, typeTrack: deepWater}, 
{track: false, x: 7, y: 3, tower: false, typeTrack: deepWater}, 
{track: false, x: 8, y: 3, tower: false, typeTrack: water}, 
{track: false, x: 9, y: 3, tower: false, typeTrack: water}, 
{track: false, x: 10, y: 3, tower: false, typeTrack: grass}, 
{track: false, x: 11, y: 3, tower: false, typeTrack: grass}, 
{track: false, x: 12, y: 3, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 3, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 3, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 3, tower: false, typeTrack:roadUD}],
//Row 5
[{track: true, x: 0, y: 4, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 4, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 4, tower: false, typeTrack: roadRD}, 
{track: true, x: 3, y: 4, tower: false, typeTrack: roadLR}, 
{track: true, x: 4, y: 4, tower: false, typeTrack: roadLR}, 
{track: true, x: 5, y: 4, tower: false, typeTrack: roadLR, trackDetails: lightWaterCover}, 
{track: true, x: 6, y: 4, tower: false, typeTrack: roadLR, trackDetails: waterCover}, 
{track: true, x: 7, y: 4, tower: false, typeTrack: roadLR, trackDetails: lightWaterCover}, 
{track: true, x: 8, y: 4, tower: false, typeTrack: roadLR}, 
{track: true, x: 9, y: 4, tower: false, typeTrack: roadLR}, 
{track: true, x: 10, y: 4, tower: false, typeTrack: roadLR}, 
{track: true, x: 11, y: 4, tower: false, typeTrack: roadLD}, 
{track: false, x: 12, y: 4, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 4, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 4, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 4, tower: false, typeTrack: roadUD}],
//Row 6
[{track: true, x: 0, y: 5, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 5, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 5, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 5, tower: false, typeTrack: grass}, 
{track: false, x: 4, y: 5, tower: false, typeTrack: grass}, 
{track: false, x: 5, y: 5, tower: false, typeTrack: water}, 
{track: false, x: 6, y: 5, tower: false, typeTrack: water}, 
{track: false, x: 7, y: 5, tower: false, typeTrack: water}, 
{track: false, x: 8, y: 5, tower: false, typeTrack: grass}, 
{track: false, x: 9, y: 5, tower: false, typeTrack: grass}, 
{track: false, x: 10, y: 5, tower: false, typeTrack: grass}, 
{track: true, x: 11, y: 5, tower: false, typeTrack: roadUD}, 
{track: false, x: 12, y: 5, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 5, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 5, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 5, tower: false, typeTrack:roadUD}],
//Row 7
[{track: true, x: 0, y: 6, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 6, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 6, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 6, tower: false, typeTrack: grass}, 
{track: true, x: 4, y: 6, tower: false, typeTrack: roadRD}, 
{track: true, x: 5, y: 6, tower: false, typeTrack: roadLR}, 
{track: true, x: 6, y: 6, tower: false, typeTrack: roadLR}, 
{track: true, x: 7, y: 6, tower: false, typeTrack: roadLR}, 
{track: true, x: 8, y: 6, tower: false, typeTrack: roadLR}, 
{track: true, x: 9, y: 6, tower: false, typeTrack: roadLD}, 
{track: false, x: 10, y: 6, tower: false, typeTrack: grass}, 
{track: true, x: 11, y: 6, tower: false, typeTrack: roadUD}, 
{track: false, x: 12, y: 6, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 6, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 6, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 6, tower: false, typeTrack:roadUD}],
//Row 8
[{track: true, x: 0, y: 7, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 7, tower: false, typeTrack: grassRock}, 
{track: true, x: 2, y: 7, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 7, tower: false, typeTrack: grass}, 
{track: true, x: 4, y: 7, tower: false, typeTrack: roadUD}, 
{track: false, x: 5, y: 7, tower: false, typeTrack: grass}, 
{track: false, x: 6, y: 7, tower: false, typeTrack: grass}, 
{track: false, x: 7, y: 7, tower: false, typeTrack: grass}, 
{track: false, x: 8, y: 7, tower: false, typeTrack: grass}, 
{track: true, x: 9, y: 7, tower: false, typeTrack: roadUD}, 
{track: false, x: 10, y: 7, tower: false, typeTrack: grass}, 
{track: true, x: 11, y: 7, tower: false, typeTrack: roadUD}, 
{track: false, x: 12, y: 7, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 7, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 7, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 7, tower: false, typeTrack:roadUD}],
//Row 9
[{track: true, x: 0, y: 8, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 8, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 8, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 8, tower: false, typeTrack: grass}, 
{track: true, x: 4, y: 8, tower: false, typeTrack: roadUD}, 
{track: false, x: 5, y: 8, tower: false, typeTrack: grass}, 
{track: true, x: 6, y: 8, tower: false, typeTrack: end, trackDetails: exitIndicatorUp}, 
{track: false, x: 7, y: 8, tower: false, typeTrack: grass}, 
{track: false, x: 8, y: 8, tower: false, typeTrack: grass}, 
{track: true, x: 9, y: 8, tower: false, typeTrack: roadUD}, 
{track: false, x: 10, y: 8, tower: false, typeTrack: grass}, 
{track: true, x: 11, y: 8, tower: false, typeTrack: roadUD}, 
{track: false, x: 12, y: 8, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 8, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 8, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 8, tower: false, typeTrack:roadUD}],
//Row 10
[{track: true, x: 0, y: 9, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 9, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 9, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 9, tower: false, typeTrack: grass}, 
{track: true, x: 4, y: 9, tower: false, typeTrack: roadUD}, 
{track: false, x: 5, y: 9, tower: false, typeTrack: grass}, 
{track: true, x: 6, y: 9, tower: false, typeTrack: roadRU}, 
{track: true, x: 7, y: 9, tower: false, typeTrack: roadLR}, 
{track: true, x: 8, y: 9, tower: false, typeTrack: roadLR}, 
{track: true, x: 9, y: 9, tower: false, typeTrack: roadLU}, 
{track: false, x: 10, y: 9, tower: false, typeTrack: grass}, 
{track: true, x: 11, y: 9, tower: false, typeTrack: roadUD}, 
{track: false, x: 12, y: 9, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 9, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 9, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 9, tower: false, typeTrack:roadUD}],
//Row 11
[{track: true, x: 0, y: 10, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 10, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 10, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 10, tower: false, typeTrack: grass}, 
{track: true, x: 4, y: 10, tower: false, typeTrack: roadUD}, 
{track: false, x: 5, y: 10, tower: false, typeTrack: grass}, 
{track: false, x: 6, y: 10, tower: false, typeTrack: grass}, 
{track: false, x: 7, y: 10, tower: false, typeTrack: grass}, 
{track: false, x: 8, y: 10, tower: false, typeTrack: grass}, 
{track: false, x: 9, y: 10, tower: false, typeTrack: grass}, 
{track: false, x: 10, y: 10, tower: false, typeTrack: grass}, 
{track: true, x: 11, y: 10, tower: false, typeTrack: roadUD}, 
{track: false, x: 12, y: 10, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 10, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 10, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 10, tower: false, typeTrack:roadUD}],
//Row 12
[{track: true, x: 0, y: 11, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 11, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 11, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 11, tower: false, typeTrack: grass}, 
{track: true, x: 4, y: 11, tower: false, typeTrack: roadRU}, 
{track: true, x: 5, y: 11, tower: false, typeTrack: roadLR}, 
{track: true, x: 6, y: 11, tower: false, typeTrack: roadLR}, 
{track: true, x: 7, y: 11, tower: false, typeTrack: roadLR}, 
{track: true, x: 8, y: 11, tower: false, typeTrack: roadLR}, 
{track: true, x: 9, y: 11, tower: false, typeTrack: roadLR}, 
{track: true, x: 10, y: 11, tower: false, typeTrack: roadLR}, 
{track: true, x: 11, y: 11, tower: false, typeTrack: roadLU}, 
{track: false, x: 12, y: 11, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 11, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 11, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 11, tower: false, typeTrack:roadUD}],
//Row 13
[{track: true, x: 0, y: 12, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 12, tower: false, typeTrack: grassRock}, 
{track: true, x: 2, y: 12, tower: false, typeTrack: roadUD}, 
{track: false, x: 3, y: 12, tower: false, typeTrack: water}, 
{track: false, x: 4, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 5, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 6, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 7, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 8, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 9, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 10, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 11, y: 12, tower: false, typeTrack: grass}, 
{track: false, x: 12, y: 12, tower: false, typeTrack: grass}, 
{track: true, x: 13, y: 12, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 12, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 12, tower: false, typeTrack:roadUD}],
//Row 14
[{track: true, x: 0, y: 13, tower: false, typeTrack: roadUD},
{track: false, x: 1, y: 13, tower: false, typeTrack: grass}, 
{track: true, x: 2, y: 13, tower: false, typeTrack: roadRU}, 
{track: true, x: 3, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 4, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 5, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 6, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 7, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 8, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 9, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 10, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 11, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 12, y: 13, tower: false, typeTrack: roadLR}, 
{track: true, x: 13, y: 13, tower: false, typeTrack: roadLU}, 
{track: false, x: 14, y: 13, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 13, tower: false, typeTrack:roadUD}],
//Row 15
[{track: true, x: 0, y: 14, tower: false, typeTrack: roadUD}, 
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass},
{track: false, x: 14, y: 14, tower: false, typeTrack: grass}, 
{track: true, x: 15, y: 14, tower: false, typeTrack:roadUD}],
//Row 16
[{track: true, x: 0, y: 15, tower: false, typeTrack: roadRU},
{track: true, x: 1, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 2, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 3, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 4, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 5, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 6, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 7, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 8, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 9, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 10, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 11, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 12, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 13, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 14, y: 15, tower: false, typeTrack: roadLR}, 
{track: true, x: 15, y: 15, tower: false, typeTrack:roadLU}]


];